#!/usr/bin/env node
/**
 * carapace-generate-cli — Build-time generator for OpenClaw plugins.
 *
 * Reads a plugin's createEntry() metadata and emits:
 *   - dist/bin/<plugin-id>.js  — standalone CLI entry point
 *   - dist/adapter.js          — OpenClaw adapter (always identical, no source file needed)
 *   - openclaw.plugin.json     — plugin manifest (derived from createEntry() + package.json)
 *
 * Usage:
 *   carapace-generate-cli --entry ./dist/plugin.js --out ./dist/bin
 *   carapace-generate-cli --entry ./dist/plugin.js --out ./dist/bin --name my-tool
 */

import { writeFileSync, mkdirSync, readFileSync } from "node:fs";
import { resolve, relative, dirname, sep } from "node:path";
import { pathToFileURL } from "node:url";
import type { PluginEntry } from "./index.js";

// ---------------------------------------------------------------------------
// Arg parsing
// ---------------------------------------------------------------------------

function parseGeneratorArgs(): { entry: string; outDir: string; name?: string } {
  const args = process.argv.slice(2);
  let entry = "";
  let outDir = "";
  let name: string | undefined;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--entry" && args[i + 1]) entry = args[++i];
    else if (args[i] === "--out" && args[i + 1]) outDir = args[++i];
    else if (args[i] === "--name" && args[i + 1]) name = args[++i];
  }

  if (!entry || !outDir) {
    console.error("Usage: carapace-generate-cli --entry <path-to-dist/index.js> --out <output-dir> [--name <bin-name>]");
    process.exit(1);
  }

  return { entry: resolve(entry), outDir: resolve(outDir), name };
}

// ---------------------------------------------------------------------------
// Path helper
// ---------------------------------------------------------------------------

function toPosixRelative(from: string, to: string): string {
  let rel = relative(from, to);
  if (sep === "\\") rel = rel.replaceAll("\\", "/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

// ---------------------------------------------------------------------------
// Generators
// ---------------------------------------------------------------------------

function generateCli(entry: string, outDir: string, binName: string, envPrefix: string): void {
  const relativeEntry = toPosixRelative(outDir, entry);

  const content = `#!/usr/bin/env node
// Auto-generated by carapace-plugin-sdk — do not edit
import { run } from "carapace-plugin-sdk/cli";
import { createEntry } from "${relativeEntry}";

run(createEntry(), { binName: "${binName}", envPrefix: "${envPrefix}" });
`;

  mkdirSync(outDir, { recursive: true });
  const outPath = resolve(outDir, `${binName}.js`);
  writeFileSync(outPath, content, { mode: 0o755 });
  console.log(`Generated CLI:     ${outPath}`);
}

function generateAdapter(entry: string): void {
  const adapterDir = dirname(entry);
  const relativeEntry = toPosixRelative(adapterDir, entry);

  const content = `// Auto-generated by carapace-plugin-sdk — do not edit
import { createAdapter } from "carapace-plugin-sdk";
import { createEntry } from "${relativeEntry}";

export default createAdapter(createEntry(), import.meta.url);
`;

  const outPath = resolve(adapterDir, "adapter.js");
  writeFileSync(outPath, content);
  console.log(`Generated adapter: ${outPath}`);
}

/**
 * Generate openclaw.plugin.json from createEntry() metadata + package.json.
 *
 * createEntry() is the single source of truth for:
 *   id, name, description, configSchema, contracts, activation
 *
 * version comes from package.json (it's the npm package version).
 * entry is always ./dist/adapter.js.
 *
 * The manifest is written to the current working directory (the plugin root),
 * not into dist/, because OpenClaw reads it from the installed package root.
 */
function generateManifest(pluginEntry: {
  id: string;
  name: string;
  description?: string;
  configSchema?: unknown;
  contracts?: unknown;
  activation?: unknown;
}): void {
  // Read version from package.json in the plugin's root directory.
  // process.cwd() is the plugin root when invoked via `npm run build`.
  let version = "0.0.0";
  let source: unknown = undefined;
  try {
    const pkg = JSON.parse(readFileSync(resolve(process.cwd(), "package.json"), "utf8"));
    version = pkg.version ?? version;
    if (pkg.repository) {
      // Derive source from package.json repository field
      const repo = typeof pkg.repository === "string" ? pkg.repository : pkg.repository.url ?? "";
      const match = repo.match(/(?:github\.com[/:]|^github:)([^/]+\/[^/.]+)/);
      if (match) {
        source = { canonicalRepo: match[1] };
      }
    }
  } catch {
    console.warn("Warning: could not read package.json for version — defaulting to 0.0.0");
  }

  const manifest: Record<string, unknown> = {
    id: pluginEntry.id,
    name: pluginEntry.name,
    description: pluginEntry.description ?? "",
    version,
    // The adapter is always at this path — generated by generateAdapter() above.
    entry: "./dist/adapter.js",
  };

  manifest.configSchema = pluginEntry.configSchema ?? { type: "object", properties: {} };

  if (pluginEntry.contracts) {
    manifest.contracts = pluginEntry.contracts;
  }

  // activation defaults to onStartup: true if not specified.
  manifest.activation = pluginEntry.activation ?? { onStartup: true };

  if (source) {
    manifest.source = source;
  }

  // openclaw is a host-specific extension block. Default to empty.
  manifest.openclaw = {};

  const outPath = resolve(process.cwd(), "openclaw.plugin.json");
  writeFileSync(outPath, JSON.stringify(manifest, null, 2) + "\n");
  console.log(`Generated manifest: ${outPath}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const { entry, outDir, name } = parseGeneratorArgs();

  const entryUrl = pathToFileURL(entry).href;
  const mod = await import(entryUrl);

  const createEntry = mod.createEntry ?? mod.default?.createEntry;
  if (typeof createEntry !== "function") {
    console.error(`Error: ${entry} does not export createEntry()`);
    process.exit(1);
  }

  const pluginEntry = createEntry() as PluginEntry;
  if (!pluginEntry.contracts?.tools?.length) {
    console.error(
      `Error: plugin "${pluginEntry.id ?? pluginEntry.name}" is missing contracts.tools. ` +
      `Migrate to definePlugin() from carapace-plugin-sdk.`,
    );
    process.exit(1);
  }
  const binName = name ?? pluginEntry.id;
  const envPrefix = binName.replace(/-/g, "_").toUpperCase();

  generateCli(entry, outDir, binName, envPrefix);
  generateAdapter(entry);
  generateManifest(pluginEntry);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
